### PR TITLE
Remove Pkg as a dependency

### PR DESCRIPTION
**Pull request by fredrikekre**
In recent Julia versions Pkg is not in the sysimage and therefore it can not be loaded "for free". Pkg was only used to conditionally activate the documentation environment in `LiveServer.servedocs` so the loss of functionality is basically non-existent -- it is easy enough to configure the package environment before calling `LiveServer.servedocs`.

Timings for loading LiveServer on Julia 1.12:
```
julia> @time using LiveServer # this PR
  0.448249 seconds

julia> @time using LiveServer # master
  0.743163 seconds
```

### CODE REVIEW

**Comment by fredrikekre** [comment]
Bump!

**Review by tlienart — APPROVED** [review]

**Comment by fredrikekre** [comment]
Sure! If you want to transfer it somewhere it could perhaps live in the JuliaDocs organization?

**Comment by tlienart** [comment]
added you as collaborator, happy to transfer this repo to JuliaDocs 👍 will open an issue there to get appropriate rights

**Comment by fredrikekre** [comment]
I invited you to JuliaDocs, you should be able to transfer once you join the org.

**Comment by tlienart** [comment]
All done, thanks 😀

**Pull request merged**
