### PR TITLE
fixes for 404

### PR DESCRIPTION
**Pull request by tlienart**
* react to change in the 404 file if there is any
* if a deleted file "re-appears" update the tab to show that
* if a file gets deleted, leave that tab unchanged

Note: for 3d point might be nice to eventually add a banner indicating that the file isn't there anymore.

### CODE REVIEW

**Comment by mortenpi** [comment]
With respect to #160: I didn't debug this in detail right now, but the behavior that I see now is that when the file gets deleted, it stays on the page (doesn't refresh to a 404). But it does not get refreshed when the `.html` file is re-created on disk. If I manually go in and edit the `.html` file, then the refresh works, so the refresh functionality itself is definitely working.

**Comment by tlienart** [comment]
thanks! yes I could reproduce that, I forgot to add a path in `file_watcher_task!` so that when a file "re-appears" it's marked as changed which triggers the callback. Should be fixed now.

> when the file gets deleted, it stays on the page (doesn't refresh to a 404).

I think that's what you suggested in #160 isn't it? ; we could add a banner that shows when the underlying file disappears but this would be for another PR

**Comment by mortenpi** [comment]
Alas, I unfortunately have a follow-up bug report :sweat_smile: It indeed works, except I think there is still a problem when you nuke the whole directory hierarchy (which is what Documenter does by default; it erases all of `build/`).

I do realize that this is a tricky one, since you might not be able to really reliably watch the file anymore? I guess you'd have to watch the whole directory hierarchy and re-watch sub-files whenever they created or something like that? Or maybe I'm overthinking here.

For what it's worth, it might be possible for me to work around this problem by running with `clean=false`, in which case the old files would not get erased.

**Comment by tlienart** [comment]
So in theory the fact that things are in a directory doesn't matter, could you clarify the setup a bit so I can try to reproduce? For instance this is what I just tried: a dummy folder with:

```
.
├── 404.html
├── baz.html
├── foo
│   ├── foo1.html
│   └── foo2.html
├── index.html
└── sample.jpg
```

starting `serve()` at the base of this directory, navigating in a browser to `/foo/foo1.html` then renaming `foo/` to `fooz/` 

* tab not refreshed (showing old content)
* after tab refresh 404 shown
* rename `fooz` to `foo` --> tab refreshes and shows `foo1.html` 

So this seems to work?

**Comment by mortenpi** [comment]
So I did not test it yet myself (will try tomorrow), but two thoughts:

1. The `makedocs` call isn't getting a `clean=false` by any chance? `clean=true` should be the default, but could pass explicitly just in case.
2. Could you try a different filename, like `foo.md`? Or even `bar/foo.md`? So that the `index.html` would end up deeper in the directory hierarchy.

**Comment by tlienart** [comment]
Structure of `docs`:

```
.
├── Project.toml
├── make.jl
└── src
    ├── bar
    │   └── foo.md
    └── index.md
```

content of `make.jl`

```
using Documenter
using MyExample

makedocs(
    sitename = "MyExample",
    format = Documenter.HTML(),
    modules = [MyExample],
    clean = true
)

# Documenter can also automatically deploy documentation to gh-pages.
# See "Hosting Documentation" and deploydocs() in the Documenter manual
# for more information.
#=deploydocs(
    repo = "<repository url>"
)=#
```

1. make a first time to generate build
1. launched live server in separate session; point browser to `/build/bar/foo/`
1. modify `src/bar/foo.md` 
1. make --> tab gets refreshed directly with the modification

**Comment by tlienart** [comment]
So the size of the watched folder should be irrelevant, all watched files are stored in a dictionary and I doubt a dictionary has an issue with anything below millions of entries.

What may happen is that `mtime` is unreliable on some systems and it might be good to have a fallback for that, I'll investigate a bit but I'd be surprised if it was indeed the issue (you're on Linux?)

One thing to note is that if you have a page that has assets on it, and you remove and re-add assets, the fact that an asset on a page re-appears will not trigger the parent page (that would be a significant amount of work to keep track of such dependencies) but that doesn't seem to be what you're reporting 🤔

**Comment by mortenpi** [comment]
> you're on Linux?

Yep, and standard ext4, so I wouldn't really expect the filesystem to be giving us trouble.

> One thing to note is that if you have a page that has assets on it, and you remove and re-add assets, the fact that an asset on a page re-appears will not trigger the parent page (that would be a significant amount of work to keep track of such dependencies) but that doesn't seem to be what you're reporting

Yeah, nah, the issues I'm seeing are for the page itself. I did see some messages about the assets in the LiveServer log, which made me think about that. But no, I am not expecting the page to update when assets change.

That said, theoretically it might be possible to keep track of those assets via the `Referer` header (on some sort of best-effort basis):

image

But since, at least for me, the main use case of the live updates are in the context of Documenter, in which case everything gets updated on a rebuild anyway, I don't think specifically supporting asset changes would even be something that you'd need most of the time.

**Comment by tlienart** [comment]
Wdyt, should I merge this as an improvement already and we can iterate once there's a clearer idea of the heisenbug?

**Comment by mortenpi** [comment]
Yeah, it definitely doesn't seem to break anything. Happy to continue debug the heisenbug in an issue.

**Pull request merged**
