### PR TITLE
Add `serve weave()` to update and serve weave files

### PR DESCRIPTION
**Pull request by mpf**
This is a small extension to LiveServer.jl so that it can be easily used for serving [Weave.jl](https://github.com/JunoLab/Weave.jl) files.

### CODE REVIEW

**Comment by tlienart** [comment]
Thanks a lot for this! 

I'm very glad this worked well for you and it'll definitely be useful to people. However the requirement to have Weave (or Literate) is a killer.

I believe it's possible to remove it by having the `Weave.weave` command be _evaluated_ instead of written as it is now (we don't want to use lazy loading either). I'll have a look into this over the weekend.

Thanks again for this PR!

**Comment by Moelf** [comment]
is this going somewhere?

**Comment by tlienart** [comment]
@Moelf I'm not pushing this specifically as you can use Weave via Franklin which has a similar effect (see https://franklinjl.org/demos/#015_using_weave and the code)

The comment above still holds, I don't want to add dependencies to LiveServer, so for this kind of support the path should be to provide an evaluation function for specific files (i.e. when a specific file is seen as changed, it triggers a function of that file then shows the output). 

I'm happy to review a PR to this effect and help in discussions but I currently don't have bandwidth to push this myself

**Comment by Moelf** [comment]
I think this should be something provided by Weave.jl tbh.

**Pull request closed without merging**
